/**
 * AI-powered PR code review summary.
 *
 * When a pull request is opened or updated, fetches the diff, sends it to
 * Claude for analysis, and posts a summary comment on the PR.
 *
 * Task router path: triggered by github-webhook-handler.
 * Hookdeck connection routing: triggered directly by Hookdeck.
 *
 * Source verification (GitHub HMAC) is handled by Hookdeck at the source
 * level — only authenticated events reach this task.
 *
 * Hookdeck config for connection routing:
 * - Filter: { "x-github-event": { "$eq": "pull_request" } }
 * - Destination URL: https://api.trigger.dev/api/v1/tasks/handle-pr/trigger
 */

import { task } from "@trigger.dev/sdk";
import { getPRDiff, postComment, findExistingComment, updateComment, parseRepo } from "./lib/github.js";
import { ask } from "./lib/ai.js";

const REVIEW_MARKER = "<!-- ai-review-summary -->";

interface PRPayload {
  event: string;
  action: string;
  number: number;
  pull_request: {
    title: string;
    body: string | null;
    html_url: string;
    additions: number;
    deletions: number;
    changed_files: number;
  };
  repository: {
    full_name: string;
  };
  [key: string]: unknown;
}

export const handlePR = task({
  id: "handle-pr",
  run: async (payload: PRPayload) => {
    const { owner, repo } = parseRepo(payload.repository.full_name);
    const prNumber = payload.number;
    const pr = payload.pull_request;

    console.log(`Reviewing PR #${prNumber}: ${pr.title}`);
    console.log(`  ${pr.additions} additions, ${pr.deletions} deletions, ${pr.changed_files} files`);

    // Fetch the diff
    const diff = await getPRDiff(owner, repo, prNumber);

    // Truncate very large diffs to stay within context limits
    const maxDiffLength = 50000;
    const truncatedDiff =
      diff.length > maxDiffLength
        ? diff.slice(0, maxDiffLength) + "\n\n[diff truncated]"
        : diff;

    // Ask Claude for a review summary
    const prompt = `You are a senior developer reviewing a pull request. Analyze the following diff and provide:

1. A brief summary of what changed (2-3 sentences)
2. Key observations (things that look good, potential concerns)
3. Any suggestions for improvement

Keep it concise and constructive. Focus on substance, not style nitpicks.

PR title: ${pr.title}
PR description: ${pr.body ?? "(no description)"}

Diff:
\`\`\`
${truncatedDiff}
\`\`\``;

    const review = await ask(prompt, 1500);

    // Build the comment body — the marker lets us find and update it on future pushes
    const comment = `${REVIEW_MARKER}
## AI Review Summary

${review}

---
*Generated by [Hookdeck](https://hookdeck.com) + [Trigger.dev](https://trigger.dev)*`;

    // Update the existing review comment if one exists, otherwise post a new one
    const existing = await findExistingComment(owner, repo, prNumber, REVIEW_MARKER);
    if (existing) {
      await updateComment(owner, repo, existing.id, comment);
      console.log(`Updated review comment on PR #${prNumber}`);
    } else {
      await postComment(owner, repo, prNumber, comment);
      console.log(`Posted review comment on PR #${prNumber}`);
    }

    return { prNumber, owner, repo, reviewLength: review.length };
  },
});
