import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { gzipSync } from "node:zlib";

/** How the UI previews what arrived. */
export type Preview = "image" | "audio" | "video" | "pdf" | "text" | "multipart" | "zip" | "tar" | "gzip" | "hex";

/**
 * One request sent to the Hookdeck source. `body` is what goes on the wire;
 * the receiver must get exactly these bytes back for the case to pass.
 */
export interface Case {
  id: string;
  contentType: string;
  body: Buffer;
  headers?: Record<string, string>;
  /** Appended to the source URL, e.g. the x-hookdeck-content-type override. */
  query?: Record<string, string>;
  note?: string;
  /** Not on Hookdeck's binary allowlist: also sent with the content-type override. */
  offList?: boolean;
  preview: Preview;
}

const OVERRIDE = { "x-hookdeck-content-type": "application/octet-stream" };

// Real media, generated by scripts/make-fixtures.sh
const FIXTURES = resolve(dirname(fileURLToPath(import.meta.url)), "../fixtures");
const file = (name: string): Buffer => readFileSync(resolve(FIXTURES, name));

/** Deterministic bytes that are deliberately not valid UTF-8. */
function noise(size: number, seed: number): Buffer {
  const buf = Buffer.alloc(size);
  let x = seed;
  for (let i = 0; i < size; i++) {
    x = (x * 1103515245 + 12345) & 0x7fffffff;
    buf[i] = (x >>> 16) & 0xff;
  }
  buf[0] = 0xff;
  buf[1] = 0xfe;
  return buf;
}

/** A one-page PDF. The %âãÏÓ comment marks it as binary, as real PDFs do. */
function pdf(): Buffer {
  const stream = "BT /F1 18 Tf 24 60 Td (Hookdeck binary payload test) Tj ET";
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 360 120] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>",
    `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
  ];
  const parts: Buffer[] = [Buffer.from("%PDF-1.4\n"), Buffer.from([0x25, 0xe2, 0xe3, 0xcf, 0xd3, 0x0a])];
  const offsets: number[] = [];
  let length = parts.reduce((n, p) => n + p.length, 0);
  objects.forEach((body, i) => {
    offsets.push(length);
    const obj = Buffer.from(`${i + 1} 0 obj\n${body}\nendobj\n`, "latin1");
    parts.push(obj);
    length += obj.length;
  });
  const xref = [
    "xref",
    `0 ${objects.length + 1}`,
    "0000000000 65535 f ",
    ...offsets.map((o) => `${String(o).padStart(10, "0")} 00000 n `),
    "trailer",
    `<< /Size ${objects.length + 1} /Root 1 0 R >>`,
    "startxref",
    String(length),
    "%%EOF",
  ].join("\n");
  parts.push(Buffer.from(`${xref}\n`));
  return Buffer.concat(parts);
}

// The same small record in each serialisation format: { event: "order.created", id: 42, ok: true }
const str = (s: string) => Buffer.from(s, "utf8");
const MSGPACK = Buffer.concat([
  Buffer.from([0x83, 0xa5]), str("event"), Buffer.from([0xad]), str("order.created"),
  Buffer.from([0xa2]), str("id"), Buffer.from([0x2a]),
  Buffer.from([0xa2]), str("ok"), Buffer.from([0xc3]),
]);
const CBOR = Buffer.concat([
  Buffer.from([0xa3, 0x65]), str("event"), Buffer.from([0x6d]), str("order.created"),
  Buffer.from([0x62]), str("id"), Buffer.from([0x18, 0x2a]),
  Buffer.from([0x62]), str("ok"), Buffer.from([0xf5]),
]);
// Fields 1 (string), 2 (varint), 3 (bool)
const PROTOBUF = Buffer.concat([Buffer.from([0x0a, 0x0d]), str("order.created"), Buffer.from([0x10, 0x2a, 0x18, 0x01])]);
// Record { event: string, id: long, ok: boolean }, zig-zag varints
const AVRO = Buffer.concat([Buffer.from([0x1a]), str("order.created"), Buffer.from([0x54, 0x01])]);
// (module (func (export "add") (param i32 i32) (result i32) local.get 0 local.get 1 i32.add))
const WASM = Buffer.from(
  "0061736d0100000001070160027f7f017f030201000707010361646400000a09010700200020016a0b",
  "hex",
);

function multipart(): Case {
  const boundary = "----hookdeck-binary-formats";
  const part = (name: string, filename: string, type: string, data: Buffer) =>
    Buffer.concat([
      Buffer.from(
        `--${boundary}\r\nContent-Disposition: form-data; name="${name}"; filename="${filename}"\r\nContent-Type: ${type}\r\n\r\n`,
      ),
      data,
      Buffer.from("\r\n"),
    ]);
  const body = Buffer.concat([
    Buffer.from(`--${boundary}\r\nContent-Disposition: form-data; name="kind"\r\n\r\nupload\r\n`),
    part("image", "image.png", "image/png", file("image.png")),
    part("audio", "audio.mp3", "audio/mpeg", file("audio.mp3")),
    Buffer.from(`--${boundary}--\r\n`),
  ]);
  return {
    id: "multipart-image-audio",
    contentType: `multipart/form-data; boundary=${boundary}`,
    body,
    note: "PNG and MP3 parts",
    preview: "multipart",
  };
}

const allowed = (id: string, contentType: string, body: Buffer, preview: Preview, note?: string): Case => ({
  id, contentType, body, preview, note,
});
const offList = (id: string, contentType: string, body: Buffer, preview: Preview, note?: string): Case => ({
  id, contentType, body, preview, note, offList: true,
});

/**
 * Every case, plus an `-override` copy of each off-list case sent with
 * ?x-hookdeck-content-type=application/octet-stream.
 */
export function cases(): Case[] {
  const all = baseCases();
  const overrides = all
    .filter((c) => c.offList)
    .map((c) => ({ ...c, id: `${c.id}-override`, query: OVERRIDE, note: "override", offList: false }));
  return [...all, ...overrides];
}

function baseCases(): Case[] {
  const json = Buffer.from(JSON.stringify({ event: "order.created", id: 42, ok: true }));
  return [
    // Text controls: these have always worked
    allowed("json", "application/json", json, "text", "control"),
    allowed("text", "text/plain", Buffer.from("hello world\n"), "text", "control"),

    // On the binary allowlist
    allowed("octet-stream", "application/octet-stream", noise(4096, 1), "hex"),
    allowed("pdf", "application/pdf", pdf(), "pdf"),
    allowed("png", "image/png", file("image.png"), "image"),
    allowed("jpeg", "image/jpeg", file("image.jpg"), "image"),
    allowed("webp", "image/webp", file("image.webp"), "image", "1x1 pixel"),
    multipart(),
    { ...allowed("json-gzip", "application/json", gzipSync(json), "gzip", "Content-Encoding: gzip"), headers: { "Content-Encoding": "gzip" } },

    // Audio and video: speech, voice agents, call recordings, media pipelines
    offList("mp3", "audio/mpeg", file("audio.mp3"), "audio", "Deepgram TTS callback"),
    offList("wav", "audio/wav", file("audio.wav"), "audio"),
    offList("ogg", "audio/ogg", file("audio.ogg"), "audio"),
    offList("webm-audio", "audio/webm", file("audio.webm"), "audio"),
    offList("m4a", "audio/mp4", file("audio.m4a"), "audio"),
    offList("mp4", "video/mp4", file("video.mp4"), "video"),
    offList("webm-video", "video/webm", file("video.webm"), "video"),

    // Archives and compressed bodies
    offList("zip", "application/zip", file("archive.zip"), "zip"),
    offList("gzip", "application/gzip", file("archive.gz"), "gzip", "gzipped WAV"),
    offList("tar", "application/x-tar", file("archive.tar"), "tar"),

    // Binary serialisation formats: the same small record in each
    offList("protobuf", "application/x-protobuf", PROTOBUF, "hex"),
    offList("protobuf-iana", "application/protobuf", PROTOBUF, "hex"),
    offList("cbor", "application/cbor", CBOR, "hex"),
    offList("msgpack", "application/msgpack", MSGPACK, "hex"),
    offList("avro", "application/vnd.apache.avro+binary", AVRO, "hex"),

    // Other
    offList("wasm", "application/wasm", WASM, "hex", "exports add()"),
    offList("woff2", "font/woff2", Buffer.concat([str("wOF2"), noise(2048, 41)]), "hex", "synthetic"),
  ];
}
